package com.neuedu.dao;

import com.neuedu.pojo.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    /**
     * 根据订单号查询订单信息
     * @param orderNo
     * @return
     */
    Order findOrderByOrderNo(@Param("orderNo") Long orderNo);


    /**
     * 修改订单的状态和付款时间
     * @param order
     * @return
     */
    int updateOrderStatusAndPaymentTimeByOrderNo(@Param("order") Order order);

    /**
     * 修改订单状态
     * @param orderNo
     * @return
     */
    int updateOrderByOrderNo(@Param("orderNo") Long orderNo);

    /**
     * 订单列表
     * @param userId
     * @return
     */
    List<Order> findOrderByUserId(@Param("userId") Integer userId);


    /**
     * 发货
     * @param orderNo
     * @return
     */
    int updateOrderStatusAndSendTimeByOrderNo(@Param("orderNo") Long orderNo);
}